#!/bin/bash
# Helpers that turn infra/topology.env into the files each machine needs (api-N auto-wiring).
# Sourced by deploy.sh, scale_api.sh, failover.sh. Nothing here talks to the lab.
#   . infra/topology.sh; dd_upstream; dd_tunnel_conf; dd_permitopen; dd_dsn <user> <password>
. "$(dirname "${BASH_SOURCE[0]}")/topology.env"

# api-01 = 1st entry of API_HOSTS -> local port 8001 on web-01, api-02 -> 8002, ...
dd_api_list() { local n=0; for ip in $API_HOSTS; do n=$((n+1)); printf '%02d %s %s\n' "$n" "$ip" "$((8000+n))"; done; }

dd_upstream() {   # web-01: /etc/nginx/conf.d/dd_upstream.inc
  echo "# GENERATED by infra/topology.sh from infra/topology.env — do not edit on the server"
  echo "upstream dd_api {"
  dd_api_list | while read -r n ip port; do
    printf '    server 127.0.0.1:%s max_fails=2 fail_timeout=10s;   # api-%s %s\n' "$port" "$n" "$ip"; done
  echo "    keepalive 16;"
  echo "}"
}

dd_tunnel_conf() {   # web-01: /etc/dormdesk/tunnel.conf — "<local port> <api ip>" per line
  dd_api_list | while read -r n ip port; do echo "$port $ip"; done
}

dd_permitopen() {    # bastion: the only destinations the tunnel key may open
  local out=""; for ip in $API_HOSTS; do out+="permitopen=\"$ip:8000\","; done; echo "${out%,}"
}

# libpq multi-host DSN: the API connects to whichever host is writable (target_session_attrs=read-write),
# so after a failover the API finds the new primary by itself. Short timeouts make a dead host fail fast.
dd_dsn() {
  local user=$1 pw=$2
  printf 'postgresql://%s:%s@%s:5432,%s:5432/dormdesk?sslmode=require&target_session_attrs=read-write&connect_timeout=3&tcp_user_timeout=8000&keepalives=1&keepalives_idle=10&keepalives_interval=3&keepalives_count=3' \
    "$user" "$pw" "$DB_PRIMARY" "$DB_STANDBY"
}

# swap DB_PRIMARY / DB_STANDBY in topology.env (after a failover)
dd_swap_db() {
  local f; f="$(dirname "${BASH_SOURCE[0]}")/topology.env"
  sed -i -e "s/^DB_PRIMARY=$DB_PRIMARY/DB_PRIMARY=__NEWP__/" -e "s/^DB_STANDBY=$DB_STANDBY/DB_STANDBY=$DB_PRIMARY/" \
         -e "s/^DB_PRIMARY=__NEWP__/DB_PRIMARY=$DB_STANDBY/" "$f"
  . "$f"
}

# lab instance name for an IP (console.sh restart needs the name)
dd_name() {
  case $1 in
    10.0.2.150) echo db-01 ;; 10.0.2.151) echo db-02 ;; "$STORE") echo store-01 ;; "$WEB") echo web-01 ;;
    "$MON") echo mon-01 ;; "$AI") echo ai-01 ;;
    *) local n=0; for ip in $API_HOSTS; do n=$((n+1)); [ "$ip" = "$1" ] && { printf 'api-%02d\n' $n; return; }; done
       printf 'api-%02d\n' $(( ${1##*.} - 139 )) ;;
  esac
}

# wait until an instance answers SSH again (after a console restart / create)
dd_wait_ssh() { local ip=$1 t=${2:-120} i=0; until timeout 20 ${HSSH:-hssh} "$ip" true 2>/dev/null; do i=$((i+5)); [ $i -ge "$t" ] && return 1; sleep 5; done; }

# install the boot hook (infra/remote/boot_hook.sh) on an instance and set its firewall role
dd_install_hook() {
  ${HSSH:-hssh} "$1" 'mkdir -p /etc/dormdesk && cat > /etc/dormdesk/boot.sh' < infra/remote/boot_hook.sh &&
  ${HSSH:-hssh} "$1" "ROLE=$2 sh -s" < infra/remote/install_boot_hook.sh
}
