#!/usr/bin/env python3
"""Generate demo seed SQL for DormDesk v2: 2 dorms, 3 admins, rooms with random codes, one tenancy per room,
~60 days of repair history, and data for the v2 features (bills, fines, parking, facilities, bookings,
check-ins) so every dashboard and tab has something to show on Demo Day.

Usage:  python3 tools/seed_gen.py --base-url https://dormdesk-g02.duckdns.org:10201
Writes: db/seed.generated.sql   (run as postgres on the primary database)
        demo_accounts.txt       (admin logins + room links — keep private, gitignored)
All names, numbers, plates and amounts are invented demo data. The PromptPay id is an invalid placeholder
(all zeros) so a scanned demo QR can never pay a real person.
"""
import argparse
import random
import secrets
import string
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import bcrypt

ROOT = Path(__file__).resolve().parent.parent
BKK = ZoneInfo("Asia/Bangkok")
random.seed(7)

DORMS = [
    {"name": "หอพักบ้านสบาย", "floors": 4, "per_floor": 8, "history": 45, "all_features": True},
    {"name": "The Nest Residence", "floors": 3, "per_floor": 6, "history": 18, "all_features": False},
]
ADMINS = [
    {"email": "owner.a@dormdesk.demo", "name": "คุณสมชาย (หอบ้านสบาย)", "dorms": [1]},
    {"email": "owner.b@dormdesk.demo", "name": "คุณมาลี (The Nest)", "dorms": [2]},
    {"email": "manager@dormdesk.demo", "name": "ผู้จัดการ 2 อาคาร", "dorms": [1, 2]},
]
# category ids follow the insert order in 01_schema.sql
SAMPLES = {
    1: ["ไฟในห้องน้ำดับ", "ปลั๊กไฟไม่มีไฟ", "เบรกเกอร์ตัดบ่อย"],
    2: ["ก๊อกน้ำรั่ว", "ชักโครกกดไม่ลง", "น้ำไหลอ่อนมาก", "ท่อใต้ซิงก์รั่ว"],
    3: ["แอร์ไม่เย็น", "แอร์มีน้ำหยด", "รีโมทแอร์เสีย"],
    4: ["ลิฟต์ค้างชั้น 3", "ปุ่มลิฟต์ชั้น 2 กดไม่ติด"],
    5: ["ประตูตู้เสื้อผ้าหลุด", "ลูกบิดประตูหลวม", "มุ้งลวดขาด"],
    6: ["เครื่องซักผ้าเครื่อง 2 ไม่ปั่น", "เครื่องอบผ้ากินเหรียญ"],
    7: ["พัสดุหาย", "ไม่ได้รับแจ้งพัสดุ"],
    8: ["มีรถจอดขวางช่องจอด", "ไฟลานจอดรถดับ"],
    9: ["เสียงดังจากห้องข้าง ๆ", "ขอเพิ่มถังขยะชั้น 3"],
}
WEIGHTS = {1: 10, 2: 18, 3: 22, 4: 4, 5: 12, 6: 8, 7: 6, 8: 4, 9: 5}
FIRST = ["สมชาย", "สุดา", "ณัฐ", "พิมพ์", "กิตติ", "ปราง", "ธนา", "มายด์", "อาร์ม", "ฝน", "บอส", "แพรว"]
PROV = "กรุงเทพมหานคร"


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (datetime, date)):
        return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def pw():
    alphabet = string.ascii_letters + string.digits
    return "Dd-" + "".join(secrets.choice(alphabet) for _ in range(10))


def plate():
    th = "กขคงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮ"
    return f"{random.randint(1, 9) if random.random() < .4 else ''}{random.choice(th)}{random.choice(th)} {random.randint(1000, 9999)}"


def bkk(d: date, h: int, m: int = 0) -> datetime:
    return datetime.combine(d, time(h, m), tzinfo=BKK)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default="https://dormdesk-g02.duckdns.org:10201")
    args = ap.parse_args()
    now = datetime.now(timezone.utc)
    today = now.astimezone(BKK).date()
    period = f"{today:%Y-%m}"
    prev_month = (today.replace(day=1) - timedelta(days=1))
    prev_period = f"{prev_month:%Y-%m}"
    out = ["-- generated by tools/seed_gen.py — demo data only", "SET client_min_messages = warning;", "BEGIN;",
           "TRUNCATE messages, fine_photos, fines, bill_slips, bill_edits, bill_lines, bills, meter_readings, dorm_counters, "
           "objects, guest_passes, parking_waitlist, parking_permits, booking_quota_extra, booking_bans, bookings, checkins, "
           "facilities, dorm_settings, idem_keys, notifications, admin_sessions, "
           "request_events, request_photos, requests, tenancies, dorm_categories, rooms, admin_dorms, admins, dorms, "
           "security_events RESTART IDENTITY CASCADE;"]
    accounts = ["DormDesk demo accounts (PRIVATE — do not commit)", ""]

    room_ids = {}   # dorm_id -> list of (room_id, room_no)
    rent_of = {}
    rid = 0
    for d_id, d in enumerate(DORMS, start=1):
        out.append(f"INSERT INTO dorms (id, name) VALUES ({d_id}, {q(d['name'])});")
        out.append(f"INSERT INTO dorm_categories (dorm_id, category_id, enabled) "
                   f"SELECT {d_id}, id, NOT (code = 'parking' AND {d_id} = 2) FROM categories;")
        allf = d["all_features"]
        out.append(
            "INSERT INTO dorm_settings (dorm_id, f_fitness, f_pool, f_spaces, f_parking, f_bills, f_fines, promptpay_id, "
            "common_fee, water_rate, elec_rate, fee_car, fee_moto, spots_car, spots_moto, late_fee_enabled, contact_phone, contact_email) "
            f"VALUES ({d_id}, {q(allf)}, {q(allf)}, {q(allf)}, {q(allf)}, true, {q(allf)}, '0000000000000', "
            f"{30000 if allf else 0}, 1800, 700, 80000, 30000, {20 if allf else 0}, {30 if allf else 0}, {q(allf)}, "
            f"'02-000-0{d_id}00', {q(f'office{d_id}@dorm.demo')});")
        room_ids[d_id] = []
        accounts.append(f"== {d['name']} (dorm_id {d_id}) — room links ==")
        for f in range(1, d["floors"] + 1):
            for n in range(1, d["per_floor"] + 1):
                rid += 1
                no = f"{f}{n:02d}"
                code = secrets.token_urlsafe(16)
                rent = (450000 if f <= 2 else 500000) if d_id == 1 else 650000
                rent_of[rid] = rent
                out.append(f"INSERT INTO rooms (id, dorm_id, room_no, room_code, rent) VALUES ({rid}, {d_id}, {q(no)}, {q(code)}, {rent});")
                # current tenancy id == room id (keeps the seed readable)
                started = now - timedelta(days=74 if (d_id == 1 and no == "108") else random.randint(90, 400))
                out.append(f"INSERT INTO tenancies (id, dorm_id, room_id, started_at) VALUES ({rid}, {d_id}, {rid}, {q(started)});")
                room_ids[d_id].append((rid, no))
                if n <= 3 or no in ("305", "108"):
                    accounts.append(f"  ห้อง {no}: {args.base_url}/r/{code}")
        accounts.append("")
    # room 108 of dorm 1 had a previous tenant (history demo for the owner)
    r108 = next(r for r, no in room_ids[1] if no == "108")
    out.append(f"INSERT INTO tenancies (id, dorm_id, room_id, started_at, ended_at) VALUES (1000, 1, {r108}, "
               f"{q(now - timedelta(days=500))}, {q(now - timedelta(days=75))});")

    accounts.append("== Admin logins ==")
    for a_id, a in enumerate(ADMINS, start=1):
        p = pw()
        h = bcrypt.hashpw(p.encode(), bcrypt.gensalt(rounds=12)).decode()
        out.append(f"INSERT INTO admins (id, email, display_name, password_hash) VALUES "
                   f"({a_id}, {q(a['email'])}, {q(a['name'])}, {q(h)});")
        for d_id in a["dorms"]:
            out.append(f"INSERT INTO admin_dorms (admin_id, dorm_id) VALUES ({a_id}, {d_id});")
        accounts.append(f"  {a['email']} / {p}   → dorms {a['dorms']}")

    # ---------------------------------------------------------------- repair history (as v1)
    cats, weights = list(WEIGHTS), list(WEIGHTS.values())
    req_id = 0
    for d_id, d in enumerate(DORMS, start=1):
        hot_rooms = random.sample(room_ids[d_id], 3)  # rooms that break repeatedly
        for _ in range(d["history"]):
            req_id += 1
            cat = random.choices(cats, weights)[0]
            if d_id == 2 and cat == 8:
                cat = 9
            room_id, room_no = random.choice(hot_rooms) if random.random() < 0.3 else random.choice(room_ids[d_id])
            created = now - timedelta(days=random.uniform(0, 60), hours=random.uniform(0, 12))
            age_h = (now - created).total_seconds() / 3600
            roll = random.random()
            if age_h < 30:
                status = random.choice(["received", "received", "in_progress"])
            elif roll < 0.12 and age_h < 24 * 6:
                status = "in_progress"  # a few jobs overdue > 48 h
            elif roll < 0.15:
                status = "rejected"
            else:
                status = "done"
            urgent = cat in (1, 4) or random.random() < 0.1
            fix_h = random.uniform(3, 20) if urgent else random.uniform(8, 96)
            if cat == 3:
                fix_h *= 1.6  # aircon waits for the technician
            done_at = created + timedelta(hours=fix_h) if status == "done" else None
            if done_at and done_at > now:
                done_at, status = None, "in_progress"
            ten = 1000 if room_id == r108 and created < now - timedelta(days=75) else room_id
            name = random.choice(FIRST)
            title = random.choice(SAMPLES[cat])
            out.append(
                "INSERT INTO requests (id, dorm_id, room_id, tenancy_id, category_id, title, detail, reporter_name, reporter_phone, "
                "consent_at, status, priority, tracking_token, created_at, updated_at, done_at) VALUES "
                f"({req_id}, {d_id}, {room_id}, {ten}, {cat}, {q(title)}, {q('ห้อง ' + room_no + ' — ' + title)}, {q(name)}, "
                f"{q('08' + ''.join(random.choice(string.digits) for _ in range(8)))}, {q(created)}, {q(status)}, "
                f"{q('urgent' if urgent else 'normal')}, {q(secrets.token_urlsafe(16))}, {q(created)}, "
                f"{q(done_at or created)}, {q(done_at)});")
            out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, actor, created_at) "
                       f"VALUES ({d_id}, {req_id}, NULL, 'received', 'tenant', {q(created)});")
            if status in ("in_progress", "done"):
                t1 = created + timedelta(hours=min(2, fix_h / 3))
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'received', 'in_progress', 'admin:1', {q(t1)});")
            if status == "done":
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, note, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'in_progress', 'done', 'ซ่อมเรียบร้อย', 'admin:1', {q(done_at)});")
            if status == "rejected":
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, note, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'received', 'rejected', 'แจ้งซ้ำ', 'admin:1', "
                           f"{q(created + timedelta(hours=1))});")

    # ---------------------------------------------------------------- v2: facilities (dorm 1)
    fac = [(1, "ฟิตเนส ชั้น 2", "fitness", 15, "06:00", "22:00", 60), (2, "สระว่ายน้ำ", "pool", 12, "07:00", "20:00", 60),
           (3, "ห้องส่วนกลาง A", "space", None, "09:00", "22:00", 60), (4, "ห้องส่วนกลาง B", "space", None, "09:00", "22:00", 120)]
    for i, (fid, name, kind, cap, a, b, slot) in enumerate(fac):
        out.append(f"INSERT INTO facilities (id, dorm_id, name, kind, capacity, open_from, open_to, slot_minutes, qr_token, sort) "
                   f"VALUES ({fid}, 1, {q(name)}, {q(kind)}, {q(cap)}, {q(a)}, {q(b)}, {slot}, {q(secrets.token_urlsafe(18))}, {i});")
    d1 = room_ids[1]
    # check-in history (busy hours chart): 30 days, peaks morning + evening
    cid = 0
    for back in range(30, 0, -1):
        day = today - timedelta(days=back)
        for _ in range(random.randint(8, 16)):
            cid += 1
            h = random.choices([6, 7, 8, 12, 17, 18, 19, 20], [4, 5, 3, 2, 6, 9, 8, 4])[0]
            fid = 1 if random.random() < .65 else 2
            if fid == 2 and h < 7:
                h = 7
            r, _ = random.choice(d1)
            st = bkk(day, h, random.randint(0, 59))
            out.append(f"INSERT INTO checkins (dorm_id, tenancy_id, facility_id, started_at, expires_at, checked_out_at) VALUES "
                       f"(1, {r}, {fid}, {q(st)}, {q(st + timedelta(hours=3))}, {q(st + timedelta(minutes=random.randint(40, 110)))});")
    # bookings: past (some no-shows) + upcoming
    for back in range(20, 0, -1):
        if random.random() < .5:
            continue
        day = today - timedelta(days=back)
        r, _ = random.choice(d1)
        h = random.choice([10, 13, 15, 18, 19, 20])
        st = "no_show" if random.random() < .12 else "confirmed"
        out.append(f"INSERT INTO bookings (dorm_id, tenancy_id, facility_id, starts_at, ends_at, status, confirmed_at) VALUES "
                   f"(1, {r}, 3, {q(bkk(day, h))}, {q(bkk(day, h + 1))}, {q(st)}, {q(bkk(day, h, 5) if st == 'confirmed' else None)});")
    used_slots = set()
    for k in range(6):
        day = today + timedelta(days=random.randint(1, 6))
        h = random.choice([10, 11, 13, 15, 17, 19, 20])
        if (day, h) in used_slots:
            continue
        used_slots.add((day, h))
        r, _ = random.choice(d1)
        out.append(f"INSERT INTO bookings (dorm_id, tenancy_id, facility_id, starts_at, ends_at) VALUES "
                   f"(1, {r}, 3, {q(bkk(day, h))}, {q(bkk(day, h + 1))});")

    # ---------------------------------------------------------------- v2: parking (dorm 1)
    r305 = next(r for r, no in d1 if no == "305")
    pid = 0
    for r, no in random.sample(d1, 16) + [(r305, "305")]:
        pid += 1
        vt = "car" if random.random() < .55 or no == "305" else "moto"
        out.append(f"INSERT INTO parking_permits (id, dorm_id, tenancy_id, plate, province, vtype, status, sticker, spot, fee, approved_at, "
                   f"created_at) VALUES ({pid}, 1, {r}, {q(plate())}, {q(PROV)}, {q(vt)}, 'active', {q(f'A-{pid:03d}')}, "
                   f"{q(('B' if vt == 'car' else 'M') + str(pid))}, {80000 if vt == 'car' else 30000}, {q(now - timedelta(days=60))}, "
                   f"{q(now - timedelta(days=61))});")
    for r, no in random.sample([x for x in d1 if x[0] != r305], 2):
        pid += 1
        out.append(f"INSERT INTO parking_permits (id, dorm_id, tenancy_id, plate, province, vtype, status, created_at) VALUES "
                   f"({pid}, 1, {r}, {q(plate())}, {q(PROV)}, 'moto', 'pending', {q(now - timedelta(hours=random.randint(2, 40)))});")
    for r, no in random.sample(d1, 2):
        out.append(f"INSERT INTO parking_waitlist (dorm_id, tenancy_id, vtype, created_at) VALUES (1, {r}, 'car', "
                   f"{q(now - timedelta(days=random.randint(3, 20)))});")

    # ---------------------------------------------------------------- v2: bills (both dorms) — last month paid, this month issued
    bill_id, line_id, rno = 0, 0, {1: 0, 2: 0}
    for d_id in (1, 2):
        for r, no in room_ids[d_id]:
            for per, paid in ((prev_period, True), (period, None)):
                bill_id += 1
                y, m = map(int, per.split("-"))
                due = date(y, m, 10)
                water, elec = random.randint(6, 18), random.randint(90, 260)
                lines = [("rent", "ค่าเช่าห้อง", "", rent_of[r]), ("water", "ค่าน้ำ", f"{water} หน่วย", water * 1800),
                         ("electric", "ค่าไฟ", f"{elec} หน่วย", elec * 700)]
                if d_id == 1:
                    lines.append(("common", "ค่าส่วนกลาง", "", 30000))
                total = sum(x[3] for x in lines)
                if paid is None:   # this month: most unpaid, a few already paid
                    paid = random.random() < .35 and today.day >= 3
                status = "paid" if paid else "unpaid"
                paid_at = bkk(due - timedelta(days=random.randint(0, 6)), random.randint(8, 21)) if paid else None
                receipt = None
                if paid:
                    rno[d_id] += 1
                    receipt = f"DD{d_id:02d}-{paid_at:%y%m}-{rno[d_id]:04d}"
                out.append(f"INSERT INTO bills (id, dorm_id, tenancy_id, room_id, period, kind, status, due_date, total, receipt_no, "
                           f"issued_at, paid_at) VALUES ({bill_id}, {d_id}, {r}, {r}, {q(per)}, 'monthly', {q(status)}, {q(due)}, "
                           f"{total}, {q(receipt)}, {q(bkk(date(y, m, 1), 8))}, {q(paid_at)});")
                for i, (pr, lb, nt, am) in enumerate(lines):
                    out.append(f"INSERT INTO bill_lines (dorm_id, bill_id, preset, label, note, amount, sort) VALUES "
                               f"({d_id}, {bill_id}, {q(pr)}, {q(lb)}, {q(nt)}, {am}, {i});")
                if per == period:
                    out.append(f"INSERT INTO meter_readings (dorm_id, room_id, period, water_units, elec_units) VALUES "
                               f"({d_id}, {r}, {q(per)}, {water}, {elec}) ON CONFLICT DO NOTHING;")
        out.append(f"INSERT INTO dorm_counters (dorm_id, name, value) VALUES ({d_id}, 'receipt', {rno[d_id]});")
    # previous tenant of 108 left an unpaid bill (owner history demo)
    bill_id += 1
    out.append(f"INSERT INTO bills (id, dorm_id, tenancy_id, room_id, period, kind, status, due_date, total, issued_at) VALUES "
               f"({bill_id}, 1, 1000, {r108}, {q(f'{(today - timedelta(days=90)):%Y-%m}')}, 'monthly', 'unpaid', "
               f"{q((today - timedelta(days=90)).replace(day=10))}, 450000, {q(now - timedelta(days=95))});")
    out.append(f"INSERT INTO bill_lines (dorm_id, bill_id, preset, label, amount) VALUES (1, {bill_id}, 'rent', 'ค่าเช่าห้อง', 450000);")

    # ---------------------------------------------------------------- v2: one open fine with a reply (room 305)
    out.append("INSERT INTO fines (id, dorm_id, tenancy_id, room_id, preset, title, amount, original_amount, reason, status, created_by, created_at) "
               f"VALUES (1, 1, {r305}, {r305}, 'damage', 'ทำของในห้องส่วนกลางเสียหาย', 50000, 50000, "
               f"'ขาเก้าอี้ในห้องส่วนกลาง A หัก 1 ตัว หลังการจองของห้อง 305', 'disputed', 1, {q(now - timedelta(days=2))});")
    out.append(f"INSERT INTO messages (dorm_id, tenancy_id, subject_type, subject_id, author, body, created_at) VALUES "
               f"(1, {r305}, 'fine', 1, 'admin:1', 'ค่าเปลี่ยนเก้าอี้ 500 บาทครับ', {q(now - timedelta(days=2))}),"
               f"(1, {r305}, 'fine', 1, 'tenant', 'ตอนออกจากห้องเก้าอี้ยังปกติครับ ขอดูกล้องวงจรปิดได้ไหม', {q(now - timedelta(days=1, hours=20))});")

    out.append("DO $$ BEGIN " + " ".join(
        f"PERFORM setval(pg_get_serial_sequence('{t}','id'), (SELECT max(id) FROM {t}));"
        for t in ("dorms", "admins", "rooms", "requests", "request_events", "tenancies", "facilities", "parking_permits",
                  "bills", "fines")) + " END $$;")
    out.append("COMMIT;")

    (ROOT / "db" / "seed.generated.sql").write_text("\n".join(out) + "\n", encoding="utf-8")
    (ROOT / "demo_accounts.txt").write_text("\n".join(accounts) + "\n", encoding="utf-8")
    print(f"wrote db/seed.generated.sql ({req_id} requests, {bill_id} bills) and demo_accounts.txt")


if __name__ == "__main__":
    main()
