#!/usr/bin/env python3
"""Generate demo seed SQL for DormDesk: 2 dorms, 3 admins, rooms with random codes,
and ~60 days of realistic history so the dashboard has something to show.

Usage:  python3 tools/seed_gen.py --base-url https://45.77.40.35:10201
Writes: db/seed.generated.sql   (run as postgres on db-01)
        demo_accounts.txt       (admin logins + room links — keep private, gitignored)
"""
import argparse
import random
import secrets
import string
from datetime import datetime, timedelta, timezone
from pathlib import Path

import bcrypt

ROOT = Path(__file__).resolve().parent.parent
random.seed(7)

DORMS = [
    {"name": "หอพักบ้านสบาย", "floors": 4, "per_floor": 8, "history": 45},
    {"name": "The Nest Residence", "floors": 3, "per_floor": 6, "history": 18},
]
ADMINS = [
    {"email": "owner.a@dormdesk.demo", "name": "คุณสมชาย (หอบ้านสบาย)", "dorms": [1]},
    {"email": "owner.b@dormdesk.demo", "name": "คุณมาลี (The Nest)", "dorms": [2]},
    {"email": "manager@dormdesk.demo", "name": "ผู้จัดการ 2 อาคาร", "dorms": [1, 2]},
]
# category ids follow the insert order in 01_schema.sql
SAMPLES = {
    1: ["ไฟในห้องน้ำดับ", "ปลั๊กไฟไม่มีไฟ", "เบรกเกอร์ตัดบ่อย"],
    2: ["ก๊อกน้ำรั่ว", "ชักโครกกดไม่ลง", "น้ำไหลอ่อนมาก", "ท่อใต้ซิงก์รั่ว"],
    3: ["แอร์ไม่เย็น", "แอร์มีน้ำหยด", "รีโมทแอร์เสีย"],
    4: ["ลิฟต์ค้างชั้น 3", "ปุ่มลิฟต์ชั้น 2 กดไม่ติด"],
    5: ["ประตูตู้เสื้อผ้าหลุด", "ลูกบิดประตูหลวม", "มุ้งลวดขาด"],
    6: ["เครื่องซักผ้าเครื่อง 2 ไม่ปั่น", "เครื่องอบผ้ากินเหรียญ"],
    7: ["พัสดุหาย", "ไม่ได้รับแจ้งพัสดุ"],
    8: ["มีรถจอดขวางช่องจอด", "ไฟลานจอดรถดับ"],
    9: ["เสียงดังจากห้องข้าง ๆ", "ขอเพิ่มถังขยะชั้น 3"],
}
WEIGHTS = {1: 10, 2: 18, 3: 22, 4: 4, 5: 12, 6: 8, 7: 6, 8: 4, 9: 5}
FIRST = ["สมชาย", "สุดา", "ณัฐ", "พิมพ์", "กิตติ", "ปราง", "ธนา", "มายด์", "อาร์ม", "ฝน", "บอส", "แพรว"]


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime):
        return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def pw():
    alphabet = string.ascii_letters + string.digits
    return "Dd-" + "".join(secrets.choice(alphabet) for _ in range(10))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base-url", default="https://45.77.40.35:10201")
    args = ap.parse_args()
    now = datetime.now(timezone.utc)
    out = ["-- generated by tools/seed_gen.py — demo data only", "BEGIN;",
           "TRUNCATE request_events, request_photos, requests, dorm_categories, rooms, admin_dorms, admins, dorms, "
           "security_events RESTART IDENTITY CASCADE;"]
    accounts = ["DormDesk demo accounts (PRIVATE — do not commit)", ""]

    room_ids = {}  # dorm_id -> list of (room_id, room_no)
    rid = 0
    for d_id, d in enumerate(DORMS, start=1):
        out.append(f"INSERT INTO dorms (id, name) VALUES ({d_id}, {q(d['name'])});")
        out.append(f"INSERT INTO dorm_categories (dorm_id, category_id, enabled) "
                   f"SELECT {d_id}, id, NOT (code = 'parking' AND {d_id} = 2) FROM categories;")
        room_ids[d_id] = []
        accounts.append(f"== {d['name']} (dorm_id {d_id}) — room links ==")
        for f in range(1, d["floors"] + 1):
            for n in range(1, d["per_floor"] + 1):
                rid += 1
                no = f"{f}{n:02d}"
                code = secrets.token_urlsafe(16)
                out.append(f"INSERT INTO rooms (id, dorm_id, room_no, room_code) VALUES ({rid}, {d_id}, {q(no)}, {q(code)});")
                room_ids[d_id].append((rid, no))
                if n <= 3:
                    accounts.append(f"  ห้อง {no}: {args.base_url}/r/{code}")
        accounts.append("")

    accounts.append("== Admin logins ==")
    for a_id, a in enumerate(ADMINS, start=1):
        p = pw()
        h = bcrypt.hashpw(p.encode(), bcrypt.gensalt(rounds=12)).decode()
        out.append(f"INSERT INTO admins (id, email, display_name, password_hash) VALUES "
                   f"({a_id}, {q(a['email'])}, {q(a['name'])}, {q(h)});")
        for d_id in a["dorms"]:
            out.append(f"INSERT INTO admin_dorms (admin_id, dorm_id) VALUES ({a_id}, {d_id});")
        accounts.append(f"  {a['email']} / {p}   → dorms {a['dorms']}")

    cats, weights = list(WEIGHTS), list(WEIGHTS.values())
    req_id = 0
    for d_id, d in enumerate(DORMS, start=1):
        hot_rooms = random.sample(room_ids[d_id], 3)  # rooms that break repeatedly
        for _ in range(d["history"]):
            req_id += 1
            cat = random.choices(cats, weights)[0]
            if d_id == 2 and cat == 8:
                cat = 9
            room_id, room_no = random.choice(hot_rooms) if random.random() < 0.3 else random.choice(room_ids[d_id])
            created = now - timedelta(days=random.uniform(0, 60), hours=random.uniform(0, 12))
            age_h = (now - created).total_seconds() / 3600
            roll = random.random()
            if age_h < 30:
                status = random.choice(["received", "received", "in_progress"])
            elif roll < 0.12 and age_h < 24 * 6:
                status = "in_progress"  # a few jobs overdue > 48 h
            elif roll < 0.15:
                status = "rejected"
            else:
                status = "done"
            urgent = cat in (1, 4) or random.random() < 0.1
            fix_h = random.uniform(3, 20) if urgent else random.uniform(8, 96)
            if cat == 3:
                fix_h *= 1.6  # aircon waits for the technician
            done_at = created + timedelta(hours=fix_h) if status == "done" else None
            if done_at and done_at > now:
                done_at, status = None, "in_progress"
            name = random.choice(FIRST)
            title = random.choice(SAMPLES[cat])
            out.append(
                "INSERT INTO requests (id, dorm_id, room_id, category_id, title, detail, reporter_name, reporter_phone, "
                "consent_at, status, priority, tracking_token, created_at, updated_at, done_at) VALUES "
                f"({req_id}, {d_id}, {room_id}, {cat}, {q(title)}, {q('ห้อง ' + room_no + ' — ' + title)}, {q(name)}, "
                f"{q('08' + ''.join(random.choice(string.digits) for _ in range(8)))}, {q(created)}, {q(status)}, "
                f"{q('urgent' if urgent else 'normal')}, {q(secrets.token_urlsafe(16))}, {q(created)}, "
                f"{q(done_at or created)}, {q(done_at)});")
            out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, actor, created_at) "
                       f"VALUES ({d_id}, {req_id}, NULL, 'received', 'tenant', {q(created)});")
            if status in ("in_progress", "done"):
                t1 = created + timedelta(hours=min(2, fix_h / 3))
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'received', 'in_progress', 'admin:1', {q(t1)});")
            if status == "done":
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, note, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'in_progress', 'done', 'ซ่อมเรียบร้อย', 'admin:1', {q(done_at)});")
            if status == "rejected":
                out.append(f"INSERT INTO request_events (dorm_id, request_id, from_status, to_status, note, actor, created_at) "
                           f"VALUES ({d_id}, {req_id}, 'received', 'rejected', 'แจ้งซ้ำ', 'admin:1', "
                           f"{q(created + timedelta(hours=1))});")

    for t in ("dorms", "admins", "rooms", "requests", "request_events"):
        out.append(f"SELECT setval(pg_get_serial_sequence('{t}','id'), (SELECT max(id) FROM {t}));")
    out.append("COMMIT;")

    (ROOT / "db" / "seed.generated.sql").write_text("\n".join(out) + "\n", encoding="utf-8")
    (ROOT / "demo_accounts.txt").write_text("\n".join(accounts) + "\n", encoding="utf-8")
    print(f"wrote db/seed.generated.sql ({req_id} requests) and demo_accounts.txt")


if __name__ == "__main__":
    main()
